[project]
name = "barsxml"
version = "0.1.0"
description = "Barsxml library for task_rest"
readme = "README.md"
requires-python = "==3.12.12"
dependencies = [
  "psycopg2-binary==2.9.11",
  "requests==2.27.1",
]

[dependency-groups]
dev = [
  "pytest==6.2.5",
  "pytest-env"
]